# Generated by Django 5.2.3 on 2025-06-23 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_course_thumbnail_course_thumbnail_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='thumbnail_url',
            new_name='thumbnail',
        ),
    ]
