# Generated by Django 5.2.3 on 2025-06-28 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_assignment_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='payment_status',
            field=models.CharField(default='pending', max_length=20),
        ),
    ]
