# Generated by Django 5.2.4 on 2025-07-07 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_add_remaining_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradebookentry',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='gradebookentry',
            name='course',
        ),
        migrations.RemoveField(
            model_name='gradebookentry',
            name='student',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='core_course_categor_243cf8_idx',
            old_name='core_course_categor_8b2c1c_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='core_course_status_f0af0e_idx',
            old_name='core_course_status_9b2c1c_idx',
        ),
        migrations.RenameIndex(
            model_name='course',
            new_name='core_course_is_feat_1feaec_idx',
            old_name='core_course_is_feat_9b2c1c_idx',
        ),
        migrations.AddField(
            model_name='lesson',
            name='duration',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('instructor', 'Instructor'), ('admin', 'Admin')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='enrollment',
            name='progress',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='progress',
            name='percent_complete',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.DeleteModel(
            name='GradebookEntry',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
